#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DeepSeek Research Portal HTML Generator
Converts all project markdown documents into a cohesive, modern glassmorphism Dark Tech Web App.
Uses zero external dependencies beyond standard python markdown library.
"""

import os
import re
import markdown

# Markdown is source of truth. Every entry must exist or build fails.
DOCS = [
    {
        "file": "01_speech.md",
        "html": "01_speech.html",
        "title": "01_speech · 梁文鋒四小時交流發言精校",
        "short_title": "01_ 發言精校原文",
        "tag": "LEAD / UNVERIFIED",
        "tag_class": "badge-analysis",
        "desc": "未驗證外傳轉寫（非官方）。開源、剋制、十個月回本（payback）、AGI 路線等主張的原始載體。"
    },
    {
        "file": "02_speech_deep_analysis.md",
        "html": "02_speech_deep_analysis.html",
        "title": "02_speech_deep_analysis · 梁文鋒講話心智模型拆解",
        "short_title": "02_ 講話心智模型拆解",
        "tag": "ANALYSIS",
        "tag_class": "badge-analysis",
        "desc": "將外傳發言提煉為戰略心智模型；payback≠淨利；TileLang 等為歸因主張。"
    },
    {
        "file": "03_StockWe_融資暫停串聯分析_核查.md",
        "html": "03_StockWe_融資暫停串聯分析_核查.html",
        "title": "03_StockWe_融資暫停串聯分析_核查 · 新聞事實邊界與產業評論評估",
        "short_title": "03_ 融資暫停事件核查",
        "tag": "EVIDENCE CHECK",
        "tag_class": "badge-live",
        "desc": "Bloomberg 單一匿名信源鏈；Reuters 轉載未獨立核實；StockWe 故事層分離。"
    },
    {
        "file": "05_NVIDIA_SK_美國隊聯盟_分層相位與雙循環.md",
        "html": "05_NVIDIA_SK_美國隊聯盟_分層相位與雙循環.html",
        "title": "05_NVIDIA_SK · 美國隊聯盟與分層相位",
        "short_title": "05_ NVIDIA-SK 美國隊",
        "tag": "EVENT + FRAMEWORK",
        "tag_class": "badge-live",
        "desc": "以 NVIDIA 官方公告為 fact base 的 SK 合作詮釋；友岸 H 層綁定框架。"
    },
    {
        "file": "05_1_source_NVIDIA_SK_對話輿情轉寫.md",
        "html": "05_1_source_NVIDIA_SK_對話輿情轉寫.html",
        "title": "05_1_source · NVIDIA-SK 來源與有界輿情",
        "short_title": "05_1 來源與輿情",
        "tag": "SOURCE CAPTURE",
        "tag_class": "badge-live",
        "desc": "官方 URL、平行事件分列、單一 PTT 串樣本；Grok 對話不作為 fact source。"
    },
    {
        "file": "00_inbox.md",
        "html": "00_inbox.html",
        "title": "00_inbox · 研究收件箱與碎片資料庫",
        "short_title": "00_inbox 未分類資料",
        "tag": "INBOX",
        "tag_class": "badge-live",
        "desc": "尚未升級編入主線的新聞線索、推文與臨時觀察。"
    },
    {
        "file": "README.md",
        "html": "README.html",
        "title": "README · 專案綱領與當前狀態",
        "short_title": "README 專案綱領",
        "tag": "KNOWLEDGE HUB",
        "tag_class": "badge-live",
        "desc": "專案身份、證據矩陣、Open Question 與 Next Action。"
    },
    {
        "file": "AGENTS.md",
        "html": "AGENTS.html",
        "title": "AGENTS · 作業規則與多模型角色分工",
        "short_title": "AGENTS 作業規則",
        "tag": "GOVERNANCE",
        "tag_class": "badge-analysis",
        "desc": "作業紀律、來源分級與強制鏈接輸出規範。"
    }
]

# HTML pages that may exist but must be removed if no longer generated
ORPHAN_HTML_CANDIDATES = [
    "05_NVIDIA_SK_5000億美元AI合作與市場情緒核查.html",
]

def render_navbar(active_html=""):
    links_html = ""
    for doc in DOCS:
        active = "active" if doc["html"] == active_html else ""
        links_html += f'<li><a href="{doc["html"]}" class="nav-link {active}">{doc["short_title"]}</a></li>\n'
    
    return f"""
    <nav class="navbar">
      <div class="nav-content">
        <a href="index.html" class="logo">
          <div class="logo-icon">🧠</div>
          <span>DeepSeek Research Portal</span>
        </a>
        <ul class="nav-links">
          <li><a href="index.html" class="nav-link {'active' if active_html=='index.html' else ''}">首頁導航</a></li>
          {links_html}
        </ul>
        <div>
          <span class="badge badge-analysis">Stage: ANALYSIS</span>
        </div>
      </div>
    </nav>
    """

def render_footer():
    return """
    <footer class="footer">
      <div class="footer-links">
        <a href="index.html" class="footer-link">首頁 Dashboard</a>
        <a href="README.html" class="footer-link">專案 README</a>
        <a href="AGENTS.html" class="footer-link">作業規則</a>
        <a href="https://github.com/arislee1979-afk/17_deepseek_Kimi" target="_blank" class="footer-link">GitHub Repository</a>
      </div>
      <p>💡 本專案為知識研究 Repo，與 Hub (30_investment_hub) 保持階段索引。不構成投資或交易建議。</p>
      <p style="margin-top:0.5rem;font-size:0.8rem;color:#475569;">Generated by Antigravity · Silicon Dark Cyber Theme</p>
    </footer>
    """

def build_index():
    navbar = render_navbar("index.html")
    footer = render_footer()
    
    cards_html = ""
    for doc in DOCS:
        cards_html += f"""
        <a href="{doc['html']}" class="doc-card">
          <div>
            <div class="doc-card-header">
              <span class="doc-tag">{doc['tag']}</span>
              <span style="font-size:1.1rem;">↗</span>
            </div>
            <h3 class="doc-title">{doc['title'].split(' · ')[1] if ' · ' in doc['title'] else doc['title']}</h3>
            <p class="doc-desc">{doc['desc']}</p>
          </div>
          <div class="doc-footer">
            <span>文件代號: <code>{doc['file']}</code></span>
            <span>點擊瀏覽 →</span>
          </div>
        </a>
        """

    index_content = f"""<!DOCTYPE html>
<html lang="zh-Hant">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DeepSeek 戰略心智與公開敘事研究中心 · Research Portal</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="bg-orbs">
    <div class="orb orb-1"></div>
    <div class="orb orb-2"></div>
    <div class="orb orb-3"></div>
  </div>
  
  <div class="app-container">
    {navbar}
    
    <main class="main-content">
      <!-- Hero Section -->
      <section class="hero-section">
        <h1 class="hero-title">DeepSeek 戰略心智與<span>公開敘事研究中心</span></h1>
        <p class="hero-subtitle">
          深度拆解梁文鋒四小時交流稿的戰略心智模型，釐清「剋制即戰略」與開源商業邏輯；
          獨立核查第二輪融資暫停新聞的事實邊界，分離產業二手評論的事實層與故事層。
        </p>
        <div class="hero-meta">
          <span class="badge badge-analysis">Knowledge Stage: ANALYSIS</span>
          <span class="badge badge-live">Live HTML Documentation</span>
          <span class="badge badge-analysis">Canonical: /home/arislee1979/0_project/17_deepseek_Kimi</span>
        </div>
      </section>
      
      <!-- Interactive Dashboard Widget -->
      <section class="dashboard-widget">
        <div class="widget-header">
          <div class="widget-title">
            <span>⚡ 核心心智與研究發現 (Interactive Insights)</span>
          </div>
          <div class="tab-nav">
            <button class="tab-btn active" data-tab="tab-strategy">🎯 戰略心智公式</button>
            <button class="tab-btn" data-tab="tab-finance">🛑 融資暫停核查</button>
            <button class="tab-btn" data-tab="tab-synergy">🌐 算力與商業協同</button>
          </div>
        </div>
        
        <div id="tab-strategy" class="tab-content active">
          <h3 style="font-size:1.3rem;color:#38bdf8;margin-bottom:1rem;">工作假說標籤：Maximize P(AGI) s.t. 合理利潤與團隊</h3>
          <p style="color:#f59e0b;font-size:0.85rem;margin-bottom:0.75rem;">Claim status：Attributed to 外傳轉寫 + Writer 詮釋 · 非已證目標函數 · 非正式 synthesis</p>
          <p style="color:#cbd5e1;margin-bottom:1rem;line-height:1.7;">
            <strong>歸因於未驗證外傳講話</strong>的壓縮標籤（見 <code>02_speech_deep_analysis</code>），不是公司官方目標函數。
            Critic 判定為<strong>有條件成立的詮釋</strong>：有用，但不得當已編譯執行的 OS。
          </p>
          <div style="display:grid;grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));gap:1rem;margin-top:1.5rem;">
            <div style="background:rgba(255,255,255,0.03);padding:1.2rem;border-radius:8px;border:1px solid rgba(255,255,255,0.05);">
              <h4 style="color:#f59e0b;margin-bottom:0.5rem;">🟡 開源與收入（假設鏈）</h4>
              <p style="font-size:0.9rem;color:#94a3b8;">外傳稱十個月設備回本（payback）與口頭「六倍」；≠ 已證淨利。開源⟂收入是講者條件句，非正式財務驗證。</p>
            </div>
            <div style="background:rgba(255,255,255,0.03);padding:1.2rem;border-radius:8px;border:1px solid rgba(255,255,255,0.05);">
              <h4 style="color:#38bdf8;margin-bottom:0.5rem;">🟡 不搶 C 端芝麻（歸因）</h4>
              <p style="font-size:0.9rem;color:#94a3b8;">外傳主張：不把 C 端當主線。是否長期可執行屬 Inference，非已核實行為審計。</p>
            </div>
            <div style="background:rgba(255,255,255,0.03);padding:1.2rem;border-radius:8px;border:1px solid rgba(255,255,255,0.05);">
              <h4 style="color:#10b981;margin-bottom:0.5rem;">🟡 AGI 階梯（歸因）</h4>
              <p style="font-size:0.9rem;color:#94a3b8;">外傳路線圖語言（CoT→Agent→持續學習…）。研究綱領級，非已走完的技術事實。</p>
            </div>
          </div>
        </div>
        
        <div id="tab-finance" class="tab-content">
          <h3 style="font-size:1.3rem;color:#f59e0b;margin-bottom:1rem;">事實層 vs 故事層：第二輪融資「暫停」內幕分離</h3>
          <p style="color:#cbd5e1;margin-bottom:1rem;line-height:1.7;">
            針對 2026-07-25 主流媒體傳言 DeepSeek 暫停第二輪融資事件，本專案嚴格依據 <code style="color:#f59e0b;">AGENTS.md</code> 進行信源核查與分離：
          </p>
          <div class="table-wrapper" style="margin-top:1rem;">
            <table class="custom-table">
              <thead>
                <tr>
                  <th>觀察維度</th>
                  <th>事實層 (Verifiable Facts)</th>
                  <th>故事層 (Speculative Narratives)</th>
                  <th>研究判定</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>停融資動作</strong></td>
                  <td>Bloomberg 單一匿名信源稱口頭暫停；Reuters 轉載且未能獨立核實。</td>
                  <td>「多家 mainstream 獨立互證」或「資金斷裂內部危機」。</td>
                  <td><span style="color:#f59e0b;font-weight:600;">Attributed／Unverified</span>（非官方、非獨立多方）。</td>
                </tr>
                <tr>
                  <td><strong>暫停原因</strong></td>
                  <td>同源報道指部分原因是首輪交流內容外傳。</td>
                  <td>「競爭對手惡意舉報」或「監管強力介入封殺」。</td>
                  <td><span style="color:#f59e0b;font-weight:600;">「惡意」未證實</span>；因果不可簡化。</td>
                </tr>
                <tr>
                  <td><strong>財務狀況</strong></td>
                  <td>外傳稱十個月設備回本（payback 口徑）；≠ 已證淨利／單位經濟。</td>
                  <td>「六倍淨利已驗證」或「將迫轉高溢價閉源」。</td>
                  <td><span style="color:#38bdf8;font-weight:600;">僅歸因於外傳</span>，不作財務蓋章。</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        
        <div id="tab-synergy" class="tab-content">
          <h3 style="font-size:1.3rem;color:#10b981;margin-bottom:1rem;">傑文斯／NVDA「協同」敘事（Commentary，非已驗證結果）</h3>
          <p style="color:#f59e0b;font-size:0.85rem;margin-bottom:0.75rem;">Claim status：Lead / Commentary（StockWe 等二手）· 本 repo <strong>沒有</strong> 實證資料證明「已觸發傑文斯」或「已形成商業協同底座」</p>
          <p style="color:#cbd5e1;margin-bottom:1rem;line-height:1.7;">
            二手評論常把「模型降本 → 總推理量上升 → 利好算力」串成故事。這是<strong>可討論的產業假說</strong>，不是本專案已核驗的因果結果。
          </p>
          <div style="background:rgba(245,158,11,0.08);border-left:4px solid #f59e0b;padding:1.2rem;border-radius:0 8px 8px 0;margin:1.5rem 0;">
            <p style="color:#e2e8f0;margin-bottom:0.5rem;">
              <strong>可保留的問題</strong>：單次推理變便宜時，全社會 token 總量是否上升？上升是否轉成 GPU／HBM 需求？
            </p>
            <p style="color:#94a3b8;font-size:0.9rem;">
              <strong>不可寫成</strong>：「DeepSeek 已觸發傑文斯悖論」「總算力已加速上升」「已與 NVIDIA 形成商業協同底座」。政策收緊對華 GPU 時，「協同」會立刻變成張力（見 <code>03</code> 故事層打折）。
            </p>
          </div>
        </div>
      </section>
      
      <!-- Document Archive Grid -->
      <h2 class="section-heading">📑 專案研究文獻庫 (Research Document Archive)</h2>
      <div class="card-grid">
        {cards_html}
      </div>
      
      <!-- Evidence Base Table — mirrors README multi-dimension matrix -->
      <h2 class="section-heading">🔍 證據庫與信源矩陣（與 README 同維）</h2>
      <p style="color:#94a3b8;margin-bottom:1rem;font-size:0.9rem;">規則：分析品質高<strong>不會</strong>讓底層來源自動升級。完整表見 <a href="README.html" style="color:#38bdf8;">README.html</a>。</p>
      <div class="table-wrapper" style="margin-bottom:3.5rem;">
        <table class="custom-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>來源</th>
              <th>Source type</th>
              <th>Document role</th>
              <th>Independence</th>
              <th>Claim status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>S01</code></td>
              <td><a href="01_speech.html" style="color:#38bdf8;">01_speech.html</a> 外傳精校</td>
              <td>Lead / leak chain</td>
              <td>Raw capture</td>
              <td>Derivative</td>
              <td>Unverified attributed speech</td>
            </tr>
            <tr>
              <td><code>S03</code></td>
              <td>Bloomberg 匿名；Reuters 轉載未核實</td>
              <td>Anonymous single-source</td>
              <td>News capture</td>
              <td>非獨立互證</td>
              <td>Attributed / Unverified</td>
            </tr>
            <tr>
              <td><code>S08</code></td>
              <td><a href="https://nvidianews.nvidia.com/news/sk-group-and-nvidia-expand-strategic-partnership-across-ai-factories-and-next-generation-memory" style="color:#38bdf8;" target="_blank">NVIDIA 官方 SK 稿</a></td>
              <td>First-party official</td>
              <td>Primary event notice</td>
              <td>第一方（非落地獨立審計）</td>
              <td>Verified：已發布 LOI／計畫；Not verified：支出／訂單／2GW 落地</td>
            </tr>
            <tr>
              <td><code>S02–S07／S09–S10</code></td>
              <td>本專案分析／觀點／<code>06</code> 假說</td>
              <td>Analysis / Hypothesis</td>
              <td>Analysis · Commentary · Hypothesis</td>
              <td>Derivative of S01/S03/S08</td>
              <td>Inference；不升級底層</td>
            </tr>
          </tbody>
        </table>
      </div>
      
    </main>
    
    {footer}
  </div>
  
  <script src="script.js"></script>
</body>
</html>"""
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(index_content)
    print("✓ Successfully generated index.html")

def _docs_path_to_html():
    """Exact DOCS manifest path → generated HTML. No basename fallback."""
    by_path = {}
    for doc in DOCS:
        by_path[doc["file"]] = doc["html"]
        by_path[doc["file"].lstrip("./")] = doc["html"]
    return by_path


def md_link_to_html(raw_text: str) -> str:
    """Rewrite *local* Markdown links that are **exactly** in DOCS to .html outputs.

    Critical: the regex captures the path *without* the ``.md`` suffix, so we
    rebuild ``target_md = stem + ".md"`` before looking up the manifest.

    Rules:
    - Only exact normalized paths in DOCS map (e.g. ``01_speech.md``,
      ``05_NVIDIA_SK_美國隊聯盟_分層相位與雙循環.md``).
    - **No basename fallback**: ``bogus/01_speech.md`` and typo dirs stay
      unchanged so the verifier can fail the build.
    - Cross-repo (``../…``) and absolute URLs are left untouched.
    """
    by_path = _docs_path_to_html()

    def repl(m):
        stem = m.group(1)  # path without .md
        anchor = m.group(2) or ""
        original = m.group(0)

        if stem.startswith("http://") or stem.startswith("https://"):
            return original
        if stem.startswith("../") or stem.startswith("/"):
            return original

        target_md = stem[2:] if stem.startswith("./") else stem
        if not target_md.endswith(".md"):
            target_md = target_md + ".md"

        if target_md in by_path:
            return f"({by_path[target_md]}{anchor})"

        # Unknown / typo path: keep .md so verify_local_href rejects it in HTML
        return original

    return re.sub(
        r"\((?!https?://)(\.?/?[\w\-_\./\u4e00-\u9fa5]+)\.md(#[\w\-_\.]*)?\)",
        repl,
        raw_text,
    )


def verify_local_href(href, path_exists=os.path.exists):
    """Return error reason if local href is invalid for the site; else None.

    Rejects (Issue #3):
    - extension-less local paths (``01_speech``)
    - residual ``*.md`` (must be mapped to generated ``*.html``)
    - any missing full relative path (``ghost/01_speech.html``) — **no**
      basename allowlist that would false-negative when only the leaf name
      matches a known page
    """
    if href.startswith(("#", "http://", "https://", "mailto:", "data:")):
        return None

    path = href.split("?")[0].split("#")[0]
    if not path:
        return None

    base = os.path.basename(path)

    # extension-less: "01_speech"
    if "." not in base and not path.endswith("/"):
        return "extension-less local href (likely md→html bug)"

    # site pages must not point at Markdown sources
    if base.endswith(".md") or path.endswith(".md"):
        return "local .md href residual (must map to generated .html)"

    # full relative path must exist — basename matching a known page is NOT enough
    if not path_exists(path):
        return "target file missing"

    return None


def verify_internal_links():
    """Fail build if any generated HTML has invalid local hrefs."""
    html_files = [d["html"] for d in DOCS] + ["index.html"]
    broken = []
    href_re = re.compile(r'href="([^"]+)"')

    for html_file in html_files:
        if not os.path.exists(html_file):
            broken.append((html_file, "<file missing>", "generated page absent"))
            continue
        with open(html_file, "r", encoding="utf-8") as f:
            text = f.read()
        for href in href_re.findall(text):
            why = verify_local_href(href)
            if why:
                broken.append((html_file, href, why))

    if broken:
        print("✗ Broken internal links:")
        for src, href, why in broken:
            print(f"  - {src}: href={href!r} ({why})")
        raise SystemExit(f"Build failed: {len(broken)} broken internal link(s)")

    print(f"✓ Internal link check passed ({len(html_files)} HTML pages)")


def run_self_tests():
    """Minimal regression tests (Issue #3). Fail build if any assertion breaks."""
    errors = []

    def check(cond, msg):
        if not cond:
            errors.append(msg)

    # --- md_link_to_html: exact manifest only ---
    check(
        md_link_to_html("[a](01_speech.md)") == "[a](01_speech.html)",
        "01_speech.md should map to 01_speech.html",
    )
    check(
        md_link_to_html("[c](05_1_source_NVIDIA_SK_對話輿情轉寫.md)")
        == "[c](05_1_source_NVIDIA_SK_對話輿情轉寫.html)",
        "05_1_source_*.md should map to matching .html",
    )
    check(
        md_link_to_html("[b](bogus/01_speech.md)") == "[b](bogus/01_speech.md)",
        "bogus/01_speech.md must NOT basename-fallback to 01_speech.html",
    )
    check(
        md_link_to_html("[r](reviews/02_critic_review.md)")
        == "[r](reviews/02_critic_review.md)",
        "deleted/typo paths must NOT basename-fallback to a known page",
    )
    check(
        md_link_to_html("[e](https://example.com/x.md)") == "[e](https://example.com/x.md)",
        "absolute URLs must be left untouched",
    )
    check(
        md_link_to_html("[f](../20_china-overcapacity/foo.md)")
        == "[f](../20_china-overcapacity/foo.md)",
        "cross-repo ../ paths must be left untouched",
    )

    # --- verify_local_href: no false negatives ---
    def exists_none(_p):
        return False

    def exists_only_readme(p):
        return p == "README.md" or p.endswith("/README.md")

    why = verify_local_href("ghost/01_speech.html", path_exists=exists_none)
    check(why == "target file missing", f"ghost/01_speech.html must fail, got {why!r}")

    why = verify_local_href("README.md", path_exists=exists_only_readme)
    check(
        why == "local .md href residual (must map to generated .html)",
        f"README.md residual must fail even if file exists, got {why!r}",
    )

    why = verify_local_href("01_speech", path_exists=exists_none)
    check(
        why == "extension-less local href (likely md→html bug)",
        f"extension-less must fail, got {why!r}",
    )

    why = verify_local_href("01_speech.html", path_exists=lambda p: p == "01_speech.html")
    check(why is None, f"valid 01_speech.html must pass, got {why!r}")

    why = verify_local_href("https://example.com/a.html", path_exists=exists_none)
    check(why is None, "absolute https must pass")

    if errors:
        print("✗ Self-tests failed:")
        for e in errors:
            print(f"  - {e}")
        raise SystemExit(f"Build failed: {len(errors)} self-test(s) failed")

    print("✓ Self-tests passed (md_link mapping + verify_local_href cases)")


def build_docs():
    md = markdown.Markdown(extensions=['tables', 'fenced_code', 'toc', 'nl2br'])
    missing = []

    for doc in DOCS:
        md_file = doc["file"]
        html_file = doc["html"]
        if not os.path.exists(md_file):
            missing.append(md_file)
            print(f"✗ ERROR: source missing: {md_file}")
            continue

        with open(md_file, "r", encoding="utf-8") as f:
            raw_text = f.read()

        converted_text = md_link_to_html(raw_text)

        md.reset()
        html_body = md.convert(converted_text)

        toc_items = ""
        header_idx = 0

        def replace_header(match):
            nonlocal header_idx, toc_items
            tag = match.group(1)
            content = match.group(2)
            clean_text = re.sub(r'<[^>]+>', '', content).strip()
            h_id = f"h-{header_idx}-" + re.sub(r'[^\w\u4e00-\u9fa5]', '', clean_text)[:20]
            header_idx += 1

            indent = "0" if tag == 'h1' else ("12px" if tag == 'h2' else "24px")
            toc_items += f'<li><a href="#{h_id}" class="sidebar-link" style="margin-left: {indent};">{clean_text}</a></li>\n'
            return f'<{tag} id="{h_id}">{content}</{tag}>'

        updated_html_body = re.sub(r'<(h[123])>(.*?)</\1>', replace_header, html_body, flags=re.DOTALL)

        other_docs_html = ""
        for od in DOCS:
            if od["html"] != html_file:
                other_docs_html += f'<li><a href="{od["html"]}" class="sidebar-link" style="color:#38bdf8;">📄 {od["short_title"]}</a></li>\n'

        navbar = render_navbar(html_file)
        footer = render_footer()

        page_html = f"""<!DOCTYPE html>
<html lang="zh-Hant">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{doc['title']} · DeepSeek Research Portal</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="bg-orbs">
    <div class="orb orb-1" style="opacity: 0.1;"></div>
    <div class="orb orb-2" style="opacity: 0.1;"></div>
  </div>
  
  <div class="app-container">
    {navbar}
    
    <main class="main-content">
      <div style="margin-bottom: 1.5rem;">
        <a href="index.html" style="color:var(--text-secondary);text-decoration:none;font-size:0.9rem;">← 返回研究導航首頁</a>
      </div>
      
      <div class="doc-layout">
        <aside class="sidebar">
          <div class="sidebar-title">📑 本文目錄導覽</div>
          <ul class="sidebar-nav" style="margin-bottom: 2rem;">
            {toc_items}
          </ul>
          
          <div class="sidebar-title">📁 其他相關報告</div>
          <ul class="sidebar-nav">
            {other_docs_html}
          </ul>
        </aside>
        
        <article class="markdown-body">
          {updated_html_body}
        </article>
      </div>
    </main>
    
    {footer}
  </div>
  
  <script src="script.js"></script>
</body>
</html>"""
        with open(html_file, "w", encoding="utf-8") as f:
            f.write(page_html)
        print(f"✓ Successfully generated {html_file}")

    if missing:
        raise SystemExit(f"Build failed: {len(missing)} source file(s) missing: {missing}")


def clean_orphan_html():
    expected = {d["html"] for d in DOCS} | {"index.html"}
    for name in ORPHAN_HTML_CANDIDATES:
        if name not in expected and os.path.exists(name):
            os.remove(name)
            print(f"🗑 Removed orphan HTML: {name}")


if __name__ == "__main__":
    print("🚀 Starting HTML generation for DeepSeek Research Portal...")
    run_self_tests()
    build_index()
    build_docs()
    clean_orphan_html()
    verify_internal_links()
    print("🎉 All HTML site files generated successfully!")
